# 认证服务基础配置
server:
  port: 8081 # 服务端口

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: your_password
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    database: 0

# JWT配置
jwt:
  secret: your_jwt_secret
  expiration: 3600 # 秒

# 日志级别
logging:
  level:
    root: INFO 