server:
  port: 9091

spring:
  application:
    name: llm-serve
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  
  # R2DBC PostgreSQL Configuration
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/ai_xone
    username: ai_xone
    password: ai_xone
    properties:
      schema: ai_xone
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m

  # Flyway Configuration for Database Migration
  flyway:
    url: jdbc:postgresql://127.0.0.1:5432/ai_xone
    user: ai_xone
    password: ai_xone
    schemas: ai_xone
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
  
  # Nacos Configuration
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        access-key: serverIdentity
        secret-key: security
        context-path: /nacos
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: public
        group: DEFAULT_GROUP
        access-key: serverIdentity
        secret-key: security
        context-path: /nacos

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      modelService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  ratelimiter:
    instances:
      modelService:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 5s

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.r2dbc.connection: DEBUG
    org.springframework.r2dbc.connection.ConnectionFactoryUtils: TRACE
    org.springframework.r2dbc.core.DefaultDatabaseClient: TRACE