# event-center 基础配置
server:
  port: 8080 # 服务端口

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventcenter
    username: eventcenter
    password: eventcenter
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # 开发环境自动建表
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    root: INFO
    com.aixone.eventcenter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*' # 开放所有监控端点
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
