export default {
    'User management': '用户管理',
    'User list': '用户列表',
    'Add user': '添加用户',
    'Edit user': '编辑用户',
    'Delete user': '删除用户',
    'Username': '用户名',
    'Email': '邮箱',
    'Password': '密码',
    'Status': '状态',
    'Organization': '组织',
    'Department': '部门',
    'Position': '岗位',
    'Roles': '角色',
    'Create time': '创建时间',
    'Updated at': '更新时间',
    'Active': '激活',
    'Inactive': '停用',
    'Suspended': '暂停',
    'User details': '用户详情',
    'Assign departments': '分配部门',
    'Assign positions': '分配岗位',
    'Assign roles': '分配角色',
}
