spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_center_dev
    username: postgres
    password: postgres
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 1
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848

# 开发环境日志配置
logging:
  level:
    com.aixone.metacenter: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 开发环境元数据服务配置
meta:
  center:
    cache:
      enabled: false
    multi-tenant:
      enabled: false
    permission:
      enabled: false
    event:
      enabled: false 