server:
  port: 8080
  servlet:
    context-path: /api/meta-center

spring:
  application:
    name: meta-center
  
  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:5432/meta_center
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1
      leak-detection-threshold: 60000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  
  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1小时
      cache-null-values: false
  
  # 日志配置
  logging:
    level:
      com.aixone.metacenter: DEBUG
      org.springframework.data.jpa: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
      name: logs/meta-center.log
      max-size: 100MB
      max-history: 30

# 元数据服务配置
meta:
  center:
    # 缓存配置
    cache:
      meta-object: 7200 # 元数据对象缓存时间（秒）
      meta-attribute: 7200 # 元数据属性缓存时间（秒）
      meta-relation: 7200 # 元数据关系缓存时间（秒）
      meta-rule: 1800 # 元数据规则缓存时间（秒）
      meta-extension: 3600 # 元数据扩展缓存时间（秒）
    
    # 规则引擎配置
    rule-engine:
      aviator:
        cache-size: 1000
        max-cache-size: 2000
        enable-cache: true
    
    # 流程引擎配置
    process-engine:
      max-instance-count: 10000
      cleanup-interval: 3600 # 清理间隔（秒）
    
    # 权限服务配置
    permission-service:
      cache-enabled: true
      cache-ttl: 1800 # 权限缓存时间（秒）
    
    # 数据服务配置
    data-service:
      batch-size: 1000
      max-query-time: 30000 # 最大查询时间（毫秒）
    
    # UI服务配置
    ui-service:
      template-cache-enabled: true
      template-cache-ttl: 3600 # 模板缓存时间（秒）

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# 健康检查配置
health:
  redis:
    enabled: true
  db:
    enabled: true 