export default {
    'User management': 'User Management',
    'User list': 'User List',
    'Add user': 'Add User',
    'Edit user': 'Edit User',
    'Delete user': 'Delete User',
    'Username': 'Username',
    'Email': 'Email',
    'Password': 'Password',
    'Status': 'Status',
    'Organization': 'Organization',
    'Department': 'Department',
    'Position': 'Position',
    'Roles': 'Roles',
    'Create time': 'Create Time',
    'Updated at': 'Updated At',
    'Active': 'Active',
    'Inactive': 'Inactive',
    'Suspended': 'Suspended',
    'User details': 'User Details',
    'Assign departments': 'Assign Departments',
    'Assign positions': 'Assign Positions',
    'Assign roles': 'Assign Roles',
}
