server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: axione-tech-auth
  
  # 使用H2内存数据库进行测试
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # 禁用Flyway
  flyway:
    enabled: false
  
  # 禁用Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10s

# JWT配置
jwt:
  secret: ${JWT_SECRET:aixone-tech-auth-secret-key-for-jwt-token-generation-and-validation}
  expiration: 3600000  # 1小时
  refresh-expiration: 604800000  # 7天
  issuer: aixone-tech-auth

# 多租户配置
multitenant:
  enabled: true
  default-tenant: default
  tenant-header: X-Tenant-ID

# 安全配置
security:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
  
  rate-limit:
    enabled: false  # 禁用限流

# 日志配置
logging:
  level:
    com.aixone.tech.auth: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
